apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tokentonative
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: {{ .Release.Service }}
type: Opaque
data:
  bridgeOwnerKey: {{ .Values.tokenToNativeKeys.bridgeOwner.key | b64enc }}
{{ if .Values.tokenToNativeKeys.bridgeOwner.password }}
  bridgeOwnerPassword: {{ .Values.tokenToNativeKeys.bridgeOwner.password | b64enc }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nativetotoken
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: {{ .Release.Service }}
type: Opaque
data:
  bridgeOwnerKey: {{ .Values.nativeToTokenKeys.bridgeOwner.key | b64enc }}
{{ if .Values.nativeToTokenKeys.bridgeOwner.password }}
  bridgeOwnerPassword: {{ .Values.nativeToTokenKeys.bridgeOwner.password | b64enc }}
{{ end }}
  tokenHolderKey: {{ .Values.nativeToTokenKeys.tokenHolder.key | b64enc }}
{{ if .Values.nativeToTokenKeys.tokenHolder.password }}
  tokenHolderPassword: {{ .Values.nativeToTokenKeys.tokenHolder.password | b64enc }}
{{ end }}
