// Code generated by "stringer -type=TransferState"; DO NOT EDIT.

package testapp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Failed-1]
	_ = x[Success-2]
}

const _TransferState_name = "FailedSuccess"

var _TransferState_index = [...]uint8{0, 6, 13}

func (i TransferState) String() string {
	i -= 1
	if i < 0 || i >= TransferState(len(_TransferState_index)-1) {
		return "TransferState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TransferState_name[_TransferState_index[i]:_TransferState_index[i+1]]
}
