// Code generated by "stringer -type=TransferType"; DO NOT EDIT.

package testapp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Deposit-1]
	_ = x[Withdraw-2]
}

const _TransferType_name = "DepositWithdraw"

var _TransferType_index = [...]uint8{0, 7, 15}

func (i TransferType) String() string {
	i -= 1
	if i < 0 || i >= TransferType(len(_TransferType_index)-1) {
		return "TransferType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TransferType_name[_TransferType_index[i]:_TransferType_index[i+1]]
}
